#page title
page_title                                :   Mailo - Mailo to Self                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1177705087                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Mailo                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Email yourself fast, easy and secure.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kate Belinskaya                                
your_link                                 : https://ameba.co                    
your_city                                 : Washington DC                                
email_address                             : info@ameba.co
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : amebalabs
github_username                           : 
youtube_username                          :


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Mail to Self
    description                           : Notes, URLs, ToDo's... Open app, type and tap Send, as easy as it gets.
    fontawesome_icon_name                 : envelope
    
  - title                                 : Gmail Native
    description                           : Assign labels and read status, control the email subject and signature, save presets for different use cases.
    fontawesome_icon_name                 : mail-bulk

  - title                                 : Siri Shortcuts
    description                           : Use Mailo actions in Shortcuts apps.
    fontawesome_icon_name                 : microphone

  - title                                 : Today Widget
    description                           : Send clipboard content with one tap from Today Widget.
    fontawesome_icon_name                 : th

  - title                                 : Share Sheet
    description                           : Send links to your inbox with one tap, works from Safari, News/RSS apps and more.
    fontawesome_icon_name                 : share-square

  - title                                 : Dark Mode
    description                           : Support for dark mode makes, mail to self in complete darkness.
    fontawesome_icon_name                 : moon



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#fe9501"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#fe9501"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown